# Generated by Django 5.2.5 on 2025-09-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seller_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
