# Generated by Django 5.2.6 on 2025-09-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='social_medias',
            field=models.URLField(blank=True, null=True),
        ),
    ]
