# Generated by Django 5.2.6 on 2025-09-28 10:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_seller_social_medias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='social_medias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), blank=True, default=list, size=None),
        ),
    ]
